/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated/settings/connections'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSettingsApiDocsRouteImport } from './routes/_authenticated/settings/api-docs'
import { Route as ApiPublicV1RemindersRouteImport } from './routes/api/public/v1/reminders'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicV1ClientsRouteImport } from './routes/api/public/v1/clients'
import { Route as ApiPublicV1CallLogsRouteImport } from './routes/api/public/v1/call-logs'
import { Route as ApiPublicV1WebhooksInboundRouteImport } from './routes/api/public/v1/webhooks/inbound'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsApiDocsRoute =
  AuthenticatedSettingsApiDocsRouteImport.update({
    id: '/settings/api-docs',
    path: '/settings/api-docs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicV1RemindersRoute = ApiPublicV1RemindersRouteImport.update({
  id: '/api/public/v1/reminders',
  path: '/api/public/v1/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClientsRoute = ApiPublicV1ClientsRouteImport.update({
  id: '/api/public/v1/clients',
  path: '/api/public/v1/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CallLogsRoute = ApiPublicV1CallLogsRouteImport.update({
  id: '/api/public/v1/call-logs',
  path: '/api/public/v1/call-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1WebhooksInboundRoute =
  ApiPublicV1WebhooksInboundRouteImport.update({
    id: '/api/public/v1/webhooks/inbound',
    path: '/api/public/v1/webhooks/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/api/mcp': typeof ApiMcpRoute
  '/invite/$code': typeof InviteCodeRoute
  '/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/api/public/v1/call-logs': typeof ApiPublicV1CallLogsRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/reminders': typeof ApiPublicV1RemindersRoute
  '/api/public/v1/webhooks/inbound': typeof ApiPublicV1WebhooksInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/api/mcp': typeof ApiMcpRoute
  '/invite/$code': typeof InviteCodeRoute
  '/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/api/public/v1/call-logs': typeof ApiPublicV1CallLogsRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/reminders': typeof ApiPublicV1RemindersRoute
  '/api/public/v1/webhooks/inbound': typeof ApiPublicV1WebhooksInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/api/mcp': typeof ApiMcpRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_authenticated/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/api/public/v1/call-logs': typeof ApiPublicV1CallLogsRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/reminders': typeof ApiPublicV1RemindersRoute
  '/api/public/v1/webhooks/inbound': typeof ApiPublicV1WebhooksInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/history'
    | '/onboarding'
    | '/reminders'
    | '/api/mcp'
    | '/invite/$code'
    | '/settings/api-docs'
    | '/settings/api-keys'
    | '/settings/connections'
    | '/settings/organization'
    | '/api/public/v1/call-logs'
    | '/api/public/v1/clients'
    | '/api/public/v1/me'
    | '/api/public/v1/reminders'
    | '/api/public/v1/webhooks/inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/history'
    | '/onboarding'
    | '/reminders'
    | '/api/mcp'
    | '/invite/$code'
    | '/settings/api-docs'
    | '/settings/api-keys'
    | '/settings/connections'
    | '/settings/organization'
    | '/api/public/v1/call-logs'
    | '/api/public/v1/clients'
    | '/api/public/v1/me'
    | '/api/public/v1/reminders'
    | '/api/public/v1/webhooks/inbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/reminders'
    | '/api/mcp'
    | '/invite/$code'
    | '/_authenticated/settings/api-docs'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/connections'
    | '/_authenticated/settings/organization'
    | '/api/public/v1/call-logs'
    | '/api/public/v1/clients'
    | '/api/public/v1/me'
    | '/api/public/v1/reminders'
    | '/api/public/v1/webhooks/inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  InviteCodeRoute: typeof InviteCodeRoute
  ApiPublicV1CallLogsRoute: typeof ApiPublicV1CallLogsRoute
  ApiPublicV1ClientsRoute: typeof ApiPublicV1ClientsRoute
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
  ApiPublicV1RemindersRoute: typeof ApiPublicV1RemindersRoute
  ApiPublicV1WebhooksInboundRoute: typeof ApiPublicV1WebhooksInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/api-docs': {
      id: '/_authenticated/settings/api-docs'
      path: '/settings/api-docs'
      fullPath: '/settings/api-docs'
      preLoaderRoute: typeof AuthenticatedSettingsApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/reminders': {
      id: '/api/public/v1/reminders'
      path: '/api/public/v1/reminders'
      fullPath: '/api/public/v1/reminders'
      preLoaderRoute: typeof ApiPublicV1RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clients': {
      id: '/api/public/v1/clients'
      path: '/api/public/v1/clients'
      fullPath: '/api/public/v1/clients'
      preLoaderRoute: typeof ApiPublicV1ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/call-logs': {
      id: '/api/public/v1/call-logs'
      path: '/api/public/v1/call-logs'
      fullPath: '/api/public/v1/call-logs'
      preLoaderRoute: typeof ApiPublicV1CallLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/inbound': {
      id: '/api/public/v1/webhooks/inbound'
      path: '/api/public/v1/webhooks/inbound'
      fullPath: '/api/public/v1/webhooks/inbound'
      preLoaderRoute: typeof ApiPublicV1WebhooksInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSettingsApiDocsRoute: typeof AuthenticatedSettingsApiDocsRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSettingsApiDocsRoute: AuthenticatedSettingsApiDocsRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMcpRoute: ApiMcpRoute,
  InviteCodeRoute: InviteCodeRoute,
  ApiPublicV1CallLogsRoute: ApiPublicV1CallLogsRoute,
  ApiPublicV1ClientsRoute: ApiPublicV1ClientsRoute,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
  ApiPublicV1RemindersRoute: ApiPublicV1RemindersRoute,
  ApiPublicV1WebhooksInboundRoute: ApiPublicV1WebhooksInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
