// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzfewoitwlsclmyrymrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZmV3b2l0d2xzY2xteXJ5bXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4NzE3NDgsImV4cCI6MjA5NzQ0Nzc0OH0.M5r8EJ5uUlYEMeVofju728IcCE6aj45FyWJ0wxtbqpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});